name: deploy

on:
  workflow_call:
    inputs:
      environmentType:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      laResourceGroup:
        required: true
        type: string
      laName:
        required: true
        type: string
      workspaceId:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  validate:
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v3
     - uses: azure/login@v1
       name: Sign in to Azure
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     - if: inputs.environmentType != 'Production'
       uses: azure/arm-deploy@v1
       name: Run preflight validation
       with:
         deploymentName: ${{ github.run_number }}
         resourceGroupName: ${{ inputs.resourceGroupName }}
         template: ./Deploy/main.bicep
         parameters: >
           laResourceGroup=${{ inputs.laResourceGroup }}
           laName=${{ inputs.laName }}
           workspaceId=${{ inputs.workspaceId }}
         deploymentMode: Validate
     - if: inputs.environmentType == 'Production'
       uses: azure/arm-deploy@v1
       name: Run what-if
       with:
         failOnStdErr: false
         resourceGroupName: ${{ inputs.resourceGroupName }}
         template: ./Deploy/main.bicep
         parameters: >
           laResourceGroup=${{ inputs.laResourceGroup }}
           laName=${{ inputs.laName }}
           workspaceId=${{ inputs.workspaceId }}
         additionalArguments: --what-if
 
  deploy:
    needs: validate
#    environment: ${{ inputs.environmentType }}
    runs-on: ubuntu-latest
    outputs:
      dceURI: ${{ steps.deployBicep.outputs.dceURI }}
      dcrImmutableId: ${{ steps.deployBicep.outputs.dcrImmutableId }}
      functionAppName: ${{ steps.deployBicep.outputs.functionAppName }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - uses: azure/arm-deploy@v1
      id: deployBicep
      name: Deploy Bicep file
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./Deploy/main.bicep
        parameters: >
           laResourceGroup=${{ inputs.laResourceGroup }}
           laName=${{ inputs.laName }}
           workspaceId=${{ inputs.workspaceId }}
    - name: Run Azure PowerShell script
      id: getPublishingProfile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $publishingProfile = Get-AzWebAppPublishingProfile -ResourceGroupName ${{ inputs.resourceGroupName }} -Name ${{ steps.deployBicep.outputs.functionAppName }}
          echo "publishingProfile=$publishingProfile" >> $GITHUB_OUTPUT
        azPSVersion: "latest"


  deploy-fa:
    needs: deploy
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'fnapp6f7hsy2ymlle2' # ${{ needs.deploy.outputs.functionAppName }}
          slot-name: 'Production'
          package: '.' # ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # publish-profile: ${{ secrets.PUBPROF }} # ${{ needs.deploy.outputs.publishingProfile }}
          publisch-profile: '<publishData><publishProfile profileName="fnapp6f7hsy2ymlle2 - Web Deploy" publishMethod="MSDeploy" publishUrl="fnapp6f7hsy2ymlle2.scm.azurewebsites.net:443" msdeploySite="fnapp6f7hsy2ymlle2" userName="$fnapp6f7hsy2ymlle2" userPWD="7i2mh40NdxTTKZtlNbsXZ7PapaSrRcgfmZYiapb1T3lAnQE4TtksS4u04sgA" destinationAppUrl="https://fnapp6f7hsy2ymlle2.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="fnapp6f7hsy2ymlle2 - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-am2-487.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="fnapp6f7hsy2ymlle2\$fnapp6f7hsy2ymlle2" userPWD="7i2mh40NdxTTKZtlNbsXZ7PapaSrRcgfmZYiapb1T3lAnQE4TtksS4u04sgA" destinationAppUrl="https://fnapp6f7hsy2ymlle2.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="fnapp6f7hsy2ymlle2 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="fnapp6f7hsy2ymlle2.scm.azurewebsites.net:443" userName="$fnapp6f7hsy2ymlle2" userPWD="7i2mh40NdxTTKZtlNbsXZ7PapaSrRcgfmZYiapb1T3lAnQE4TtksS4u04sgA" destinationAppUrl="https://fnapp6f7hsy2ymlle2.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'