name: deploy

on:
  workflow_call:
    inputs:
      environmentType:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      laResourceGroup:
        required: true
        type: string
      laName:
        required: true
        type: string
      workspaceId:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  validate:
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v3
     - uses: azure/login@v1
       name: Sign in to Azure
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     - if: inputs.environmentType != 'Production'
       uses: azure/arm-deploy@v1
       name: Run preflight validation
       with:
         deploymentName: ${{ github.run_number }}
         resourceGroupName: ${{ inputs.resourceGroupName }}
         template: ./Deploy/main.bicep
         parameters: >
           laResourceGroup=${{ inputs.laResourceGroup }}
           laName=${{ inputs.laName }}
           workspaceId=${{ inputs.workspaceId }}
         deploymentMode: Validate
     - if: inputs.environmentType == 'Production'
       uses: azure/arm-deploy@v1
       name: Run what-if
       with:
         failOnStdErr: false
         resourceGroupName: ${{ inputs.resourceGroupName }}
         template: ./Deploy/main.bicep
         parameters: >
           laResourceGroup=${{ inputs.laResourceGroup }}
           laName=${{ inputs.laName }}
           workspaceId=${{ inputs.workspaceId }}
         additionalArguments: --what-if
 
  deploy:
    needs: validate
#    environment: ${{ inputs.environmentType }}
    runs-on: ubuntu-latest
    outputs:
      dceURI: ${{ steps.deployBicep.outputs.dceURI }}
      dcrImmutableId: ${{ steps.deployBicep.outputs.dcrImmutableId }}
      functionAppName: ${{ steps.deployBicep.outputs.functionAppName }}
      publishingProfile: ${{ steps.getPublishingProfile.publishingProfile}}
      test1: ${{ steps.getPublishingProfile.test1}}
      test2: ${{ steps.getPublishingProfile.test2}}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - uses: azure/arm-deploy@v1
      id: deployBicep
      name: Deploy Bicep file
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./Deploy/main.bicep
        parameters: >
           laResourceGroup=${{ inputs.laResourceGroup }}
           laName=${{ inputs.laName }}
           workspaceId=${{ inputs.workspaceId }}
    - name: Run Azure CLI script
      id: getPublishingProfile
      run: |
        echo publishingProfile=$(az webapp deployment list-publishing-profiles --resource-group ${{ inputs.resourceGroupName }} --name ${{ steps.deployBicep.outputs.functionAppName }} --xml) >> $GITHUB_OUTPUT


  deploy-fa:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Echo'
        run: |
          echo 'Hello' 
          echo 'Hello: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
          echo 'functionAppName ${{ needs.deploy.outputs.functionAppName }}'
          echo 'PP:  ${{ needs.deploy.outputs.publishingProfile }}'
          echo 'output1: ${{ needs.deploy.outputs.test1 }}'
          echo 'output2: ${{ needs.deploy.outputs.test2 }}'
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          # app-name: 'fnapp6f7hsy2ymlle2'
          app-name: ${{ needs.deploy.outputs.functionAppName }}
          slot-name: 'Production'
          package: '.' # ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # publish-profile: '${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
          publish-profile: ${{ needs.deploy.outputs.publishingProfile }}