name: lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lint code
      run: |
        az bicep build --file Deploy/main.bicep