# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure Function App

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

env:
    AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
    resourceGroupName: RG-VMCountFADev
    laResourceGroup: DefaultResourceGroup-WEU
    laName: DefaultWorkspace-30483fd2-311e-4847-81bf-4fa79f8f8f44-WEU
    workspaceId: ab431c8494a14886aa0576f01ea23b5a

jobs:

  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml
    