# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Log Running VMs end-to-end

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.json'
      - 'main.yml'
  workflow_dispatch:

jobs:

  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  # Deploy to the test environment.
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    needs: lint
    with:
      environmentType: Test
      region: westeurope
      managementGroupId: c493edd7-d41b-49ea-960c-ca7c9cfec95b # Root management Group
      subscriptionId: 30483fd2-311e-4847-81bf-4fa79f8f8f44 # Target Subscription
      resourceGroupName: RG-FA-LOGVM-TST
      faName: kostoso-logvm-tst
      laResourceGroup: DefaultResourceGroup-WEU
      laName: DefaultWorkspace-30483fd2-311e-4847-81bf-4fa79f8f8f44-WEU
      workspaceId: ab431c8494a14886aa0576f01ea23b5a
      subscriptionsToMonitor: '30483fd2-311e-4847-81bf-4fa79f8f8f44,67aa3a00-7f19-49c3-9c46-5d6d3c508072'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Deploy to the Production environment.
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: [lint,deploy-test]
    with:
      environmentType: Production
      region: westeurope
      managementGroupId: c493edd7-d41b-49ea-960c-ca7c9cfec95b # Root management Group
      subscriptionId: 30483fd2-311e-4847-81bf-4fa79f8f8f44 # Target Subscription
      resourceGroupName: RG-FA-LOGVM-PRD
      faName: kostoso-logvm-prd
      laResourceGroup: rg-loganalytics
      laName: LATest
      workspaceId: 09f7e607809e4b22b23f74136fc3d501
      subscriptionsToMonitor: '30483fd2-311e-4847-81bf-4fa79f8f8f44,67aa3a00-7f19-49c3-9c46-5d6d3c508072'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}